sudo: required

services:
    - docker

before_install:
    - docker pull opendataservices/resourceprojects.org-frontend
    - docker build -t opendataservices/resourceprojects.org-frontend .

script:
    - true

after_success:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - if [[ $TRAVIS_PULL_REQUEST -eq "false" ]]; then docker tag opendataservices/resourceprojects.org-frontend opendataservices/resourceprojects.org-frontend:${TRAVIS_TAG:-$TRAVIS_BRANCH}; docker push opendataservices/resourceprojects.org-frontend:${TRAVIS_TAG:-$TRAVIS_BRANCH}; fi
